Fix build on macOS
Without this build fails on macOS with
> ./store.go:1561:12: undefined: directory.Size
> ./store.go:1566:11: undefined: directory.Size
because directory.Size has no implementation.

Signed-off-by: Miloslav Trmač <mitr@redhat.com>