composefs: add parent directory if missing
it solves this error with mkcomposefs when the TOC doesn't specify the
parent directory for an entry:

Error: committing the finished image: failed to put layer using a partial pull: failed to convert json to erofs: exit status 1: mkcomposefs: Parent directory missing for /usr/share/locale/ca/LC_MESSAGES/libc.mo

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>