INCOMPATIBLE: Remove the implementation of the ostree transport
Currently, ostree does not compile:

> ostree/ostree_dest.go:115:28: cannot use d (variable of type *ostreeImageDestination) as private.ImageDestinationInternalOnly value in argument to impl.AddCompat: *ostreeImageDestination does not implement private.ImageDestinationInternalOnly (missing method NoteOriginalOCIConfig) (typecheck)
> 	d.Compat = impl.AddCompat(d)

This has been broken since fa1baa1893136b75e35e18150ea61d150d8f1c06 (Nov 18 2024, > 4 months).

Previously:
- 2afd63ed124bd6f8fa1e6ff6655daddf9950aa5e (broken almost 4 months),
- fa3ee4329a716a9f9fb05d50bcc5b63f3cc25a99 (broken > 7 months)

Overall, it seems extremely likely that noone is using the
containers_image_ostree build tag (off by default since March 2019).

So, finally, give up, and delete the code. Most importantly, this allows us
to delete the > 3-year-old-frozen dependency, and risky CGo code.

Signed-off-by: Miloslav Trmač <mitr@redhat.com>